# Main build jobs for CI/CD on Azure Pipelines.

parameters:
- name: builds
  type: object
  default:

  - name: linux_39
    vmImage: ubuntu-22.04
    vars:
      PYTHON_SERIES: "3.9"

  - name: macos_39
    vmImage: macos-12
    vars:
      PYTHON_SERIES: "3.9"

  - name: windows_39
    vmImage: windows-2022
    vars:
      PYTHON_SERIES: "3.9"

jobs:
- ${{ each build in parameters.builds }}:
  - job: ${{ format('build_{0}', build.name) }}
    pool:
      vmImage: ${{ build.vmImage }}
    variables:
      ${{ insert }}: ${{ build.vars }}
    steps:

    - template: azure-job-setup.yml
      parameters:
        setupBuild: true

    - bash: |
        set -euo pipefail
        source activate-conda.sh
        set -x
        \conda create -y -n build jupyter-packaging setuptools pip python="$PYTHON_SERIES"
        conda activate build
        pip install $BASH_WORKSPACE/sdist/*.tar.gz
      displayName: Install from sdist

    - bash: |
        set -euo pipefail
        source activate-conda.sh
        conda activate build
        set -x

        # uh, TODO: test this for real somehow???
        python -c 'import wwt_kernel_data_relay'
      displayName: Test

- job: docs
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      set -x
      \conda create -y -n build jupyter-packaging setuptools pip python=3.9
      conda activate build
      pip install $BASH_WORKSPACE/sdist/*.tar.gz
    displayName: Install from sdist

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      \conda install -y numpydoc sphinx sphinx-automodapi
      pip install astropy-sphinx-theme
      cd docs
      make html
      make linkcheck
    displayName: Build docs
